server:
  port: 80
#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://127.0.0.1:3306/ssm
#  username: root
#  password: 599995
logging:
  level:
    com.example: debug
    org.springframework: info

#使用hikari数据库连接池
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 599995
  #配置 redis
  redis:
    host: localhost
    port: 6379

# mybatis配置
mybatis:
  #配置实体类 别名包路径
  type-aliases-package: com.example.pojo
  # 配置映射文件
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 在控制台输出执行sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

